name: Testing Token

permissions: write-all
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run token -- ${{ secrets.GITHUB_TOKEN }}
    - run: sleep 3600
